#!/bin/bash
#
# This script is designed to be run inside the container
#

# fail hard and fast even on pipelines
set -eo pipefail

sysctl vm.overcommit_memory=1 > /dev/null

/app/bin/redis-server /etc/redis/redis.conf
